[chore]:

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -7,10 +7,9 @@
 set -euo pipefail
 
 sys_target=$(uname)
-arch=$(uname -m)
 case "$sys_target" in
     Linux) ;;
-    *) echo "OS Not Supported: $uname_s" ;;
+    *) echo "OS Not Supported: $sys_target" ;;
 esac
 
 current_script_path=${BASH_SOURCE[0]}
@@ -23,13 +22,24 @@ mkdir -p "$ASDF_DOWNLOAD_PATH"
 
 # Download file to the download directory
 echo "* Downloading $TOOL_NAME release $ASDF_INSTALL_VERSION..."
-gh release download "$ASDF_INSTALL_VERSION" --clobber --repo "$GH_REPO" --dir "${ASDF_DOWNLOAD_PATH}" || fail "Could not download ceptre"
+( gh release \
+    download "$ASDF_INSTALL_VERSION" \
+    --clobber \
+    --repo "$GH_REPO" \
+    --dir "${ASDF_DOWNLOAD_PATH}"
+  ) || fail "Could not download ceptre"
 
 tar_name="${TOOL_NAME}-${sys_target}"
 bin_name="${TOOL_NAME}-bin"
+
+echo "* Unzipping Release"
 unzip -o "${ASDF_DOWNLOAD_PATH}/${sys_target}"*.zip -d "$ASDF_DOWNLOAD_PATH"
-echo "Unpacking Binary"
+
+echo "* Unpacking Binary"
 tar -xzf "$ASDF_DOWNLOAD_PATH/${sys_target}/${tar_name,,}.tgz" -C "$ASDF_DOWNLOAD_PATH" || fail "Could not extract ceptre"
+
+echo "* Renaming Binary"
 mv "$ASDF_DOWNLOAD_PATH/${bin_name}" "$ASDF_DOWNLOAD_PATH/ceptre"
 
+echo "* Cleaning Up"
 rm "${ASDF_DOWNLOAD_PATH}"/*.zip
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -13,4 +13,20 @@ plugin_dir=$(dirname "$(dirname "$current_script_path")")
 # shellcheck source=../lib/utils.bash
 source "${plugin_dir}/lib/utils.bash"
 
-install_version "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH/bin"
+if [ "$ASDF_INSTALL_TYPE" != "ASFD_INSTALL_VERSION" ]; then
+    fail "asdf-$TOOL_NAME supports release installs only"
+fi
+
+(
+    mkdir -p "$ASDF_INSTALL_PATH/bin"
+    echo "* Copying Binary into: $ASDF_INSTALL_PATH/bin"
+    cp -r "${ASDF_DOWNLOAD_PATH}/$TOOL_NAME" "$ASDF_INSTALL_PATH/bin/"
+
+    tool_cmd="$(echo "$TOOL_TEST" | cut -d' ' -f1)"
+    test -x "$ASDF_INSTALL_PATH/bin/$tool_cmd" || fail "Expected $install_path/bin/$tool_cmd to be executable."
+
+    echo "* $TOOL_NAME $ASFD_INSTALL_VERSION installation was successful!"
+) || (
+    rm -rf "$ASDF_INSTALL_PATH"
+    fail "An error occurred while installing $TOOL_NAME $ASFD_INSTALL_VERSION."
+)
